version: '3.8'

services:
  app:
    build: .
    container_name: tcc-springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/projeto
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - tcc-network

  db:
    image: mysql:8.0
    container_name: tcc-mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tcc-network

volumes:
  mysql-data:


networks:
  tcc-network:
    driver: bridge
